name: ChiaCalculator
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 17.0
  developmentRegion: en
  knownRegions:
    - en
    - es
    - ca
    - fr
    - de
  createIntermediateGroups: true
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.chiacalculator
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: 5.10
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: "Chia Calculator"
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
targets:
  ChiaCalculator:
    type: application
    platform: iOS
    sources:
      - path: Sources
        name: Sources
      - path: Localization
        name: Localization
        buildPhase: resources
      - path: Assets.xcassets
        name: Assets
        buildPhase: resources
    settings:
      base:
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ChiaCalculatorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        name: Tests
    dependencies:
      - target: ChiaCalculator
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/ChiaCalculator.app/ChiaCalculator
        SWIFT_VERSION: 5.10
